Add task metaevaluation for nlg
neulab/ExplainaBoard pull request #527
Opened 2022-10-02 19:35 UTC by pfliu-nlp

Blocked by: https://github.com/neulab/ExplainaBoard/pull/526

Based on evaluation metrics achieved in PR 526, this PR aims to introduce task processor.

Notably,
the shape check process in function `aggregate_stats()` is still too strong: https://github.com/neulab/ExplainaBoard/blob/b31d5d6506bdb6fb633b836ef798f25488f4052d/explainaboard/metrics/metric.py#L406 I further relax it in this PR. We can discussion more about this.

2022-10-03 13:51 UTC, neubig commented
Comment: I wonder if you'd be able to use a method for aggregation like I did here?
https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/metrics/nlg_meta_evaluation.py#L115-L141

It seems that it would then be possible to avoid removing that check.

2022-10-03 23:45 UTC, odashi requested changes
You need to separate changes in metric.py from this pull request. This change requires another discussion.

Also, I don't agree with the changes in metric.py at this point because of not sufficient explanation. Could you clarify more about why the change is necessary?

2022-10-03 23:45 UTC, odashi commented on explainaboard/loaders/meta_evaluation_nlg.py
> +        please refer to `test_loaders.py`
This docstring looks redundant.

2022-10-03 23:45 UTC, odashi commented on explainaboard/loaders/meta_evaluation_nlg.py
> +        target_field_names = ['source', 'references', 'hypotheses', 'manual_scores']
Could you avoid using single quotes? mixing single/double quotes lacks consistency in the repository (especially, it reduces searchability of IDEs)

2022-10-03 23:45 UTC, odashi commented on explainaboard/loaders/meta_evaluation_nlg.py
> +                    FileLoaderField("scores_column", target_field_names[3], list),
target_field_names is used only here: it is better to use literals instead of arrays.

2022-10-03 23:45 UTC, odashi commented on explainaboard/loaders/meta_evaluation_nlg.py
> +                    FileLoaderField("auto_scores", field_name, list),
ditto: it is enough to use literals rather than a variable.

2022-10-04 00:08 UTC, pfliu-nlp commented
> Comment: I wonder if you'd be able to use a method for aggregation like I did here? https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/metrics/nlg_meta_evaluation.py#L115-L141
> 
> It seems that it would then be possible to avoid removing that check.

I think about this but don't think it could work since once we perform
```
data.reshape((data.shape[0], data.shape[-2] * data.shape[-1]))
```

@neubig It's hard for us to recover the data to its original shape. (In the above case, `data.shape[-1]` has fixed dimension and is hard-coded as `4`. In the current case, it's dynamic.  

We need to figure out a way to fix this since it also blocks the PR: https://github.com/neulab/ExplainaBoard/pull/526.

2022-10-04 00:25 UTC, odashi commented
@pfliu-nlp For a quick fix, you can also store the size of the dimension as another stats.

2022-10-04 00:54 UTC, pfliu-nlp commented
> @pfliu-nlp For a quick fix, you can also store the size of the dimension as another stats.

Yeah, that would be another solution we can consider. But if following this, I feel like the function `_aggregate_stats` and `calc_stats_from_data` have been hacked too much. How do you think @neubig

2022-10-04 00:58 UTC, odashi commented
@pfliu-nlp Yes, it is definitely a hack, but it looks better to mitigate a restriction of the methods' presuppositions.

2022-10-06 04:36 UTC, odashi commented on explainaboard/metrics/nlg_meta_evaluation.py
> +from typing import Any, Optional, Union
I think this file should be renamed to `meta_evaluation_nlg.py` to keep consistency with other files.

2022-10-06 15:49 UTC, merged